- name: Clone Repository
  hosts: Clone Repository
  gather_facts: no
  become: true
  vars:
    ansible_python_interpreter: "/usr/bin/python3.9"
  tasks:
  - name: Git Clone
    ansible.builtin.git:
      repo: https://github.com/ansible/ansible-examples.git
      dest: /var/www/html
      single_branch: yes
      version: master