- name: Copy Files to Application Server
  hosts: localhost
  gather_facts: no
  vars:
    ansible_python_interpreter: "/usr/bin/python3.9"
  tasks:
  - name: create a key pair
    copy:
      src: /home/jenkins/code
      dest: /var/www/html/
      owner: ec2-user
      mode: '0644'