- name: Clone Repository
  hosts: application_server
  gather_facts: no
  become: true
  vars:
    ansible_python_interpreter: "/usr/bin/python3.9"
  tasks:
  - name: Git Clone
    ansible.builtin.git:
      repo: https://github.com/juliocezar84/code.git
      dest: /home/ec2-user
      force: true
      single_branch: yes
      version: main
  - name: Copy Files
    ansible.builtin.copy:
      src: /home/ec2-user/
      dest: /var/www/html