- name: Copy Files to Application Server
  hosts: application_server
  gather_facts: no
  become: true
  vars:
    ansible_python_interpreter: "/usr/bin/python3.9"
  tasks:
  - name: copy files
    copy:
      force: true
      src: /home/jenkins/code/
      dest: /var/www/html
      owner: ec2-user
      mode: '0644'