- name: EC2 Instance Creation
  hosts: localhost
  gather_facts: no
  vars:
    ansible_python_interpreter: "/usr/bin/python3.9"
  tasks:
  - name: read subnet_id in properties file
    ansible.builtin.shell: grep subnet_az_a_id /home/jenkins/properties | cut -d= -f2
    register: subnet_id
  - name: show subnet_id
    debug:
      var: subnet_id
  - name: start an instance with a public IP address
    amazon.aws.ec2_instance:
      name: "ec2-webapplication-prd-useast1-001"
      key_name: "key-webapplication-prd-useast1-001"
      vpc_subnet_id: "{{subnet_id.stdout}}"
      instance_type: t2.micro
      security_group: ssh-web
      network:
        assign_public_ip: true
      image_id: ami-0fe630eb857a6ec83
      state: running
      wait: yes
    register: properties
  - name: show variables
    debug:
      var: properties
  - name: Update Ansible Hosts File
    ansible.builtin.lineinfile:
      path: /etc/ansible/hosts
      search_string: 'application_server ansible_host'
      line: application_server ansible_host={{properties.instances[0].public_ip_address}}