- name: EC2 Instance Creation
  hosts: localhost
  gather_facts: no
  vars:
    ansible_python_interpreter: "/usr/bin/python3.9"
  tasks:
  - name: start an instance with a public IP address
    amazon.aws.ec2_instance:
      name: "ec2-webapplication-prd-useast1-001"
      key_name: "key-webapplication-prd-useast1-001"
      instance_type: t2.medium
      vpc_subnet_id: subnet-070d6e690f0854178
      #security_group: "sg-webapplication-prd-useast1-001"
      network:
        assign_public_ip: true
      image_id: ami-0fe630eb857a6ec83
      state: running
      wait: yes
    register: instance_properties
  - name: show variables
    debug:
      var: instance_properties.instances[0].public_ip_address
  - name: Update Ansible Hosts File
    ansible.builtin.lineinfile:
      path: /etc/ansible/hosts
      search_string: 'application_server ansible_host'
      line: application_server ansible_host={{instance_properties.instances[0].public_ip_address}}
      
      
      subnet-070d6e690f0854178