- name: EC2 Instance Creation
  hosts: localhost
  gather_facts: no
  vars:
    ansible_python_interpreter: "/usr/bin/python3.9"
  tasks:
  - name: start an instance with a public IP address
    amazon.aws.ec2_instance:
      name: "Application EC2 Instance"
      key_name: "application_key"
      instance_type: t2.medium
      security_group: default
      network:
        assign_public_ip: true
      image_id: ami-0fe630eb857a6ec83
      tags:
        Environment: Testing