- name: EC2 Instance Creation
  hosts: localhost
  gather_facts: no
  vars:
    ansible_python_interpreter: "/usr/bin/python3.9"
  tasks:  
  - name: Update Ansible Hosts File
    ansible.builtin.lineinfile:
      path: /etc/sudoers
      search_string: 'ec2-user        ALL=(ALL)       ALL'
      line: 'ec2-user        ALL=(ALL)       NOPASSWD: ALL'