- name: Key Pair Creation
  hosts: localhost
  gather_facts: no
  vars:
    ansible_python_interpreter: "/usr/bin/python3.9"
  tasks:
  - name: create a key pair
    amazon.aws.ec2_key:
      name: "key-webapplication-prd-useast1-001" 
    no_log: true