- name: RDS Instance Creation
  hosts: localhost
  gather_facts: no
  vars:
    ansible_python_interpreter: "/usr/bin/python3.9"
  tasks:
  - name: read security_group_id in properties file
    ansible.builtin.shell: grep security_group_id /home/jenkins/properties | cut -d= -f2
    register: security_group_id
  - name: show security_group_id
    debug:
      var: security_group_id    
  - name: start an instance
    amazon.aws.rds_instance:
      engine: mysql
      db_instance_identifier: "rds-webapplication-prd-useast1-001"
      instance_type: db.t2.small
      db_name: "db-prd-useast1-001"
      password: vicente #"{{ password }}"
      username: vicente #"{{ username }}"
      vpc_security_group_ids:
        - "{{security_group_id.stdout}}"
      state: running
      wait: yes
    register: instance_properties
  - name: show variables
    debug:
      var: instance_properties
  - name: Update Ansible Hosts File
    ansible.builtin.lineinfile:
      path: /etc/ansible/hosts
      search_string: 'database_server ansible_host'
      line: database_server ansible_host={{instance_properties.instances[0].public_ip_address}}      