- name: Create Security Group
  hosts: localhost
  gather_facts: no
  vars:
    ansible_python_interpreter: "/usr/bin/python3.9" 
  tasks:
  amazon.aws.ec2_group:
  - name: ssh-web
    description: allow ssh and http
    vpc_id: "{{ vpc.vpc.id }}"
    region: ap-southeast-3
    rules:
      - proto: tcp
        ports: 22
        cidr_ip: 0.0.0.0/0
      - proto: tcp
        ports: 80
        cidr_ip: 0.0.0.0/0