- name: Create subnet for database servers
  hosts: localhost
  gather_facts: no
  vars:
    ansible_python_interpreter: "/usr/bin/python3.9" 
  tasks:
  - name: create subnet
    amazon.aws.ec2_vpc_subnet:
      state: present
      vpc_id: vpc-0a2febc34e4f13fab
      cidr: 10.10.0.0/24
    register: subnet_properties
  - name: show variables
    debug:
      var: subnet_properties
  - name: Update Properties File
    ansible.builtin.lineinfile:
      path: /home/jenkins/properties
      search_string: 'subnet_id'
      line: subnet_id={{subnet_properties.subnet.id}}      