- name: Subnet AZ A Creation
  hosts: localhost
  gather_facts: no
  vars:
    ansible_python_interpreter: "/usr/bin/python3.9"
  tasks:
  - name: read property in properties file
    ansible.builtin.shell: grep vpc_id /home/jenkins/properties | cut -d= -f2
    register: property
  - name: show property
    debug:
      var: property    
  - name: create subnet for first az
    amazon.aws.ec2_vpc_subnet:
      vpc_id: "{{property.stdout}}"
      state: present
      az: us-east-1a
      cidr: 172.31.0.0/20
    register: properties
  - name: show properties
    debug:
      var: properties    
  - name: Update Properties File
    ansible.builtin.lineinfile:
      path: /home/jenkins/properties
      search_string: 'subnet_az_a_id'
      line: subnet_az_a_id={{properties.subnet.id}}
      create: yes