- name: Create subnet for database servers
  hosts: localhost
  gather_facts: no
  vars:
    ansible_python_interpreter: "/usr/bin/python3.9" 
  tasks:
  - name: read property in properties file
    ansible.builtin.shell: grep vpc_id /home/jenkins/properties | cut -d= -f2
    register: property
  - name: show property
    debug:
      var: property  
  - name: create subnet
    amazon.aws.ec2_vpc_subnet:
      state: present
      vpc_id: "{{property.stdout}}"
      cidr: 10.10.0.0/24
    register: subnet_properties
  - name: show variables
    debug:
      var: subnet_properties
  - name: Update Properties File
    ansible.builtin.lineinfile:
      path: /home/jenkins/properties
      search_string: 'subnet_id'
      line: subnet_id={{subnet_properties.subnet.id}}
      create: yes