- name: Virtual Private Cloud Creation
  hosts: localhost
  gather_facts: no
  vars:
    ansible_python_interpreter: "/usr/bin/python3.9"
  tasks:
  - name: create VPC
    ec2_vpc_net:
      name: vpc-webapplication-prd-useast1-001
      cidr_block: 10.0.0.0/16
      region: us-east-1
      state: present
    register: properties
  - name: show properties
    debug:
      var: properties
  - name: Update Properties File
    ansible.builtin.lineinfile:
      path: /home/jenkins/properties
      search_string: 'vpc_id'
      line: vpc_id={{properties.vpc.id}}
      create: yes